default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: docker_blog_app_development
  host: db
  username: postgres
  password: password

test:
  <<: *default
  database: docker_blog_app_test
  host: db
  username: postgres
  password: password

production:
  primary: &primary_production
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>

  cache:
    <<: *primary_production
    schema_dump: db/cache_schema.rb

  queue:
    <<: *primary_production
    schema_dump: db/queue_schema.rb

  cable:
    <<: *primary_production
    schema_dump: db/cable_schema.rb